# Generated by Django 4.1.3 on 2022-12-19 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='R_user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('contact_no', models.CharField(max_length=11)),
                ('gender', models.CharField(max_length=10)),
                ('email_add', models.EmailField(max_length=100)),
                ('nid_no', models.CharField(max_length=50)),
                ('house_no', models.IntegerField()),
                ('road_no', models.IntegerField()),
                ('zip_code', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.IntegerField()),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('train_id', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('total_seat_snigdha', models.IntegerField()),
                ('total_seat_schair', models.IntegerField()),
                ('total_seat_shovan', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_of_reservation', models.DateField()),
                ('date_of_journey', models.DateTimeField()),
                ('num_of_adults', models.IntegerField()),
                ('num_of_childs', models.IntegerField()),
                ('seat_class', models.CharField(max_length=10)),
                ('from_station', models.CharField(max_length=30)),
                ('to_station', models.CharField(max_length=30)),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtrsApp.payment')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtrsApp.r_user')),
            ],
        ),
        migrations.CreateModel(
            name='Nexuspay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('card_no', models.CharField(max_length=50)),
                ('pin', models.IntegerField()),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtrsApp.payment')),
            ],
        ),
        migrations.CreateModel(
            name='Mobile_Banking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(max_length=50)),
                ('verification_code', models.IntegerField()),
                ('pin', models.IntegerField()),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtrsApp.payment')),
            ],
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField()),
                ('station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtrsApp.station')),
                ('to_station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_station_id', to='rtrsApp.station')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('card_no', models.CharField(max_length=50)),
                ('expiration_date', models.DateField()),
                ('cvv', models.CharField(max_length=50)),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtrsApp.payment')),
            ],
        ),
        migrations.CreateModel(
            name='booked_seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.IntegerField()),
                ('date_of_journey', models.DateField()),
                ('seat_class', models.CharField(max_length=50)),
                ('reservation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtrsApp.reservation')),
                ('train_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtrsApp.train')),
            ],
        ),
    ]
