# Generated by Django 4.1.3 on 2022-12-19 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtrsApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='station',
            table='station',
        ),
    ]
