# Generated by Django 4.1.3 on 2022-12-19 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtrsApp', '0003_alter_booked_seat_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='payment',
            table='payment',
        ),
    ]
