# Generated by Django 4.1.3 on 2022-12-20 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rtrsApp', '0004_alter_payment_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Train_Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('station_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtrsApp.station')),
                ('train_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rtrsApp.train')),
            ],
            options={
                'db_table': 'Train_timetable',
                'unique_together': {('train_id', 'station_id')},
            },
        ),
    ]
