# Generated by Django 4.1.3 on 2022-12-22 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtrsApp', '0005_train_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r_user',
            name='password',
            field=models.CharField(max_length=300),
        ),
    ]
