# Generated by Django 4.1.3 on 2022-12-22 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtrsApp', '0006_alter_r_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r_user',
            name='contact_no',
            field=models.CharField(max_length=15),
        ),
    ]
