# Generated by Django 4.1.3 on 2022-12-29 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtrsApp', '0007_alter_r_user_contact_no'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='train_timetable',
            unique_together=set(),
        ),
    ]
