# Generated by Django 4.1.3 on 2022-12-29 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtrsApp', '0008_alter_train_timetable_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train_timetable',
            old_name='station_id',
            new_name='station',
        ),
        migrations.RenameField(
            model_name='train_timetable',
            old_name='train_id',
            new_name='train',
        ),
        migrations.AlterUniqueTogether(
            name='train_timetable',
            unique_together={('train', 'station')},
        ),
    ]
