# Generated by Django 4.1.3 on 2022-12-29 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtrsApp', '0009_rename_station_id_train_timetable_station_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='train_timetable',
            name='direction',
            field=models.CharField(default='FROM', max_length=20),
        ),
    ]
