# Generated by Django 4.1.3 on 2022-12-29 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtrsApp', '0010_train_timetable_direction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cost',
            old_name='station_id',
            new_name='station',
        ),
        migrations.RenameField(
            model_name='cost',
            old_name='to_station_id',
            new_name='to_station',
        ),
    ]
