# Generated by Django 4.1.3 on 2022-12-29 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtrsApp', '0012_rename_train_id_booked_seat_train'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train_timetable',
            name='departure_time',
            field=models.TimeField(),
        ),
    ]
