# Generated by Django 4.1.3 on 2022-12-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtrsApp', '0013_alter_train_timetable_departure_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train_timetable',
            name='departure_time',
            field=models.CharField(max_length=20),
        ),
    ]
