# Generated by Django 4.1.3 on 2022-12-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtrsApp', '0014_alter_train_timetable_departure_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r_user',
            name='house_no',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='r_user',
            name='road_no',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='r_user',
            name='zip_code',
            field=models.CharField(max_length=15),
        ),
    ]
