# Generated by Django 4.1.3 on 2022-12-30 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtrsApp', '0015_alter_r_user_house_no_alter_r_user_road_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='payment_id',
            new_name='payment',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='user_id',
            new_name='user',
        ),
    ]
