# Generated by Django 4.1.3 on 2022-12-30 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtrsApp', '0016_rename_payment_id_reservation_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='payment',
        ),
    ]
