# Generated by Django 4.1.3 on 2022-12-30 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtrsApp', '0017_remove_reservation_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mobile_banking',
            old_name='payment_id',
            new_name='payment',
        ),
    ]
