# Generated by Django 4.1.3 on 2023-01-01 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtrsApp', '0019_rename_reservation_id_booked_seat_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nexuspay',
            old_name='payment_id',
            new_name='payment',
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='train_timetable',
            unique_together={('train', 'station', 'direction')},
        ),
    ]
