# Generated by Django 4.1.3 on 2023-01-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rtrsApp', '0020_rename_payment_id_nexuspay_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked_seat',
            name='from_station',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='booked_seat',
            name='to_station',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
