# Generated by Django 4.1.3 on 2023-01-01 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rtrsApp', '0021_booked_seat_from_station_booked_seat_to_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booked_seat',
            name='from_station',
        ),
        migrations.RemoveField(
            model_name='booked_seat',
            name='to_station',
        ),
    ]
